language: go

go:
  - 1.9.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install: true

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -type f -iname '*.go' | grep -v /math/)

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -tags=ddebug -short -race -v {.,./internal/...,./misc/...,./sql/...} >&2
