language: go

go:
  - 1.8.x
  - 1.9.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  -

script:
  - go build .
  - go test -tags=ddebug -short -race -v {.,./internal/...,./misc/...,./sql/...}
